font_size 12.4

background #000000 
# 121212


# BEGIN_KITTY_FONTS
foreground 		#ffffff 
# foreground 86ff57
#font_family		CommitMonov2_425_min4_allON_allDEF
#font_family		CommitMonov3_275_min4_allON_allDEF
font_family 		CommitMonov4_200_min4_allON_allDEF
# font_family     	Iosevka Term
# font_family     	ShureTechMono Nerd Font Mono
bold_font        	auto
italic_font      	auto
bold_italic_font 	auto
# END_KITTY_FONTS

# modify_font cell_height 117%
modify_font cell_height 100%


# modify_font baseline 2.08


window_padding_width 0
placement_strategy top-left

# test shading
background_opacity 0.85
dynamic_background_opacity yes
