font_size 12.4

background #000000 
# 121212


# BEGIN_KITTY_FONTS
font family 		Commit Mono
# font_family     	Iosevka Term
# font_family     	ShureTechMono Nerd Font Mono
bold_font        	auto
italic_font      	auto
bold_italic_font 	auto
# END_KITTY_FONTS

modify_font cell_height 120%

modify_font baseline 2.08


window_padding_width 0
placement_strategy top-left

# test shading
background_opacity 0.85
dynamic_background_opacity yes
